create table ACCOUNT (
        id integer generated by default as identity (start with 1),
        AMOUNT double not null,
        owner_id integer,
        primary key (id)
    );

 create table APP_USER (
       id integer generated by default as identity (start with 1),
        EMAIL varchar(255) not null,
        FIRST_NAME varchar(255) not null,
        LAST_NAME varchar(255) not null,
        PASSWORD varchar(255) not null,
        USERNAME varchar(255) not null,
        primary key (id)
    );

create table LOAN (
      id integer generated by default as identity (start with 1),
      AMOUNT double not null,
      END_DATE timestamp,
      PAYED_AMOUNT double not null,
      PAYOFF_TIME integer,
      RENT double not null,
      START_DATE timestamp,
      TYPE varchar(255) not null,
      owner_id integer,
      primary key (id)
  );


 alter table APP_USER
 add constraint UK_l2aubhk7g9o13bi6i4gyhxdbc unique (USERNAME);

 alter table ACCOUNT
 add constraint FK30gweo5sp4hjr72tl3rp2euj3
 foreign key (owner_id)
 references APP_USER;

 alter table LOAN
 add constraint FKn2cxrnwxtf0n9g1bpwkt8ro05
 foreign key (owner_id)
 references APP_USER;
