INSERT INTO APP_USER (id, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME)
VALUES (default, 'john@gmail.com', 'John', 'Svergja', 'hello', 123456789);


INSERT INTO LOAN (id, AMOUNT, END_DATE, owner_id, PAYED_AMOUNT, PAYOFF_TIME, RENT, START_DATE, TYPE)
VALUES (default, 190500.0, NULL, NULL, 0.0, 96, 5.4, NULL, 'STUDENT_LOAN');
